export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/',
  PRODUCTS: '/products',
  PRODUCT_DETAILS: '/products/:id',
  ADD_PRODUCT: '/products/add',
  CATEGORIES: '/categories',
  ADD_CATEGORY: '/categories/add',
  ORDERS: '/orders',
  ORDER_DETAILS: '/orders/:id',
  USERS: '/users',
  USER_DETAILS: '/users/:id',
  ADD_USER: '/users/add',
  INVENTORY: '/inventory',
  SETTINGS: '/settings',
  SETTINGS_GENERAL: '/settings/general',
  SETTINGS_PAYMENT: '/settings/payment',
  SETTINGS_NOTIFICATION: '/settings/notification',
} as const;
